# Generated by Django 3.2.9 on 2021-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_auto_20211125_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_at',
            field=models.DateTimeField(default=None),
        ),
    ]
