# Generated by Django 3.2.9 on 2021-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0004_alter_todo_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
